general:
  # if 'true' the server will be initialized as a statistics-server with r/w-permissions to the databases.
  # if 'false' the server will be initialized as a client read-only mode.
  # 'true' is necessary for the database/table creation setup and the sync_function
  # server mode tests the postgresql server for integrity and updates it if necessary
  server_mode: True
  # Print verbose output in terminal
  verbose: False
  copyright_tag: "openfuelservice geospatial statistics"
  # define amount of cpu's to be used for multiprocessing
  cpu: 5
  temporary_folder: temp
  file_folder: files
  country_codes: country_codes.csv
  country_boundaries:
    # 1st Set. Better Quality
    zip_file: TM_WORLD_BORDERS-0.3.zip
    iso2_col: ISO2
    iso3_col: ISO3
    attribution: http://thematicmapping.org/downloads/world_borders.php
    # 2nd Set. Lower Quality
    # zip_file: country_boundaries.zip
    # iso2_col: ISO_A2
    # iso3_col: ISO_A3
    # attribution: Made with Natural Earth. Free vector and raster map data @ naturalearthdata.com
  countries_table: country_data
  hash_table: hash_data
  wikipedia_car_table: wiki_cars
  wikipedia_category_table: wiki_car_categories
  # define advanced settings
  advanced_settings:
    # Ignore list for data handling
    ignore_list: ['', ',', '.', '(', ')', '-', ':', ';', '[', ']', '{', '|', '}', ';', '"', '#', '&', '*', '//', ':', '<', '=', '>','N/A']
    # Set standard vehicle type
    vehicle_type: car
    # Set standard driving style --> moderate > fast > aggressive
    driving_style: moderate
    # Set average cruise speed for driving styles --> Needed for now!
    average_speeds:
      moderate: 70
      fast: 90
    standard_epsg: 4326
    # True to calculate detailed EnvirocarSensor models --> Will download tracks at first run (Takes some time)
    detailed_sensor_models: False
    # define calculation dimensions. Ignored when detailed_sensor_models = False
    xyz_calculations: False
    # define the max slope in degrees. Ignored when xyz_calculations = False
    max_slope: 19,3
    # define the slope calculation precision. The slope data will be sorted in equal {n} intervals,
    # e.g. (max_slope: 19,3 and slope_precision: 8) = 19,3/8 = (n = 2,4125 Interval-spacing) = [0, 2.4125, 4.825, 7.2375, 9.65, 12.0625, 14.475, 16.8875, 19.3]
    slope_precision: 8
  enabled_fuel_types: ['gasoline', 'diesel']
provider_parameters:
  host: 192.168.2.27
  port: 5435
  db_name: gis
  # define the standard postgres database (needed!)
  db_postgres_name: postgres
  # set the superuser. Set a timestamp for expiration.
  # ALTER ROLE postgres LOGIN SUPERUSER INHERIT CREATEDB REPLICATION PASSWORD 'anypwd' VALID UNTIL 'YEAR-MONTH-DAY HOUR:MINUTE:SECOND';
  # ALTER ROLE postgres LOGIN SUPERUSER INHERIT CREATEDB REPLICATION PASSWORD 'QrNQo1SbK8ZBm0ui8P8J' VALID UNTIL '2018-12-14 17:00:00';
  super_admin: postgres
  su_password: QrNQo1SbK8ZBm0ui8P8J
  # define your standard user here
  admin_user: admin
  admin_password: gZwe5Nj
  # define the statistics provider each for their own.
ann_settings:
  word_lists:
    en: word_list_en
    de: word_list_german
statistics_provider:
  envirocar_provider:
    # Limits the amount of big objects (track_statistics, track measurements) to the "crawl_amount". So fast testing can be done!
    crawl_test: True
    crawl_amount: 10
    api_url: https://envirocar.org/api/stable
    model_measurements_threshold: 1500
    # set refresh date in minutes
    refresh_rate: 180
    table_names:
      phenomenons: ec_phenomenons
      tracks: ec_tracks
      tracks_statistics: ec_tracks_statistics
      tracks_measurements: ec_tracks_measurements
      tracks_features: ec_tracks_features
      sensors: ec_sensors
      sensors_statistics: ec_sensors_statistics
      average_vehicle_type_statistics: ec_average_vehicle_type_statistics
      average_manufacturer_statistics: ec_average_manufacturer_statistics
      # update_history: update_history
    geometry_column: geom
    attribution: "enviroCar – citizen science for sustainable traffic"
  eurostat_oil_provider:
    enabled: true
    # Weekly will be added to the history database to update it.
    oil_weekly_url: http://ec.europa.eu/energy/observatory/reports/latest_prices_raw_data.xlsx
    # History is queried once the database is setup. No Sync here.
    oil_history_2005:
      # Don't change this if you don't know what you are doing!
      url: http://ec.europa.eu/energy/observatory/reports/Oil_Bulletin_Prices_History.xlsx
      sheets:
        country:
          w_tax: Prices with taxes, per CTR
          wo_tax: Prices wo taxes, per CTR
        eu_general:
          w_tax: Prices with taxes, EU
          wo_tax: Prices wo taxes, EU
    oil_history_1994:
      # Don't change this if you don't know what you are doing!
      file: time_series_years_1994_2005.zip
      dataset: 1994_2005_extraction.xls
      dataset_mappings:
        # Changing the keys will def. break the code!!!
        country_code: Country_ID
        taux: taux
        date: price_date
        euro_price: Euro_Price
        euro_ht: EURO HT
        euro_ttc: EURO TTC
        euro_tva: EURO_TVA
        euro_excise: EURO_Excise
        diesel_ht: DIESEL HT
        diesel_ttc: DIESEL TTC
        diesel_tva: DIESEL_TVA
        diesel_excise: DIESEL_Excise
    # set refresh date in days
    refresh_rate: 1
    table_names:
      country_prices: es_country_prices
      general_prices: es_general_prices
    attribution: "© European Union, 1995 - today"
  misc:
    table_names:
      ec_average_category_statistics: ec_average_category_statistics
      cfd_average_category_statistics: cfd_average_category_statistics

      wikipedia_envirocar_match_table: wikicar_envirocar_matched
      wikipedia_cfd_match_table: wikicar_cfd_matched
      wikicar_page_texts: wikicar_page_texts
  carfueldata_provider:
    enabled: true
    table_names:
      carfueldata_cars: cfd_cars
    links:
      latest_data: https://carfueldata.vehicle-certification-agency.gov.uk/additional/latest_data/Euro_6_latest_12-12-2018.zip
    attribution: "http://www.dft.gov.uk - Vehicle Certification Agency"
