"""Add wikipedia base models

Revision ID: 08433c1cee9b
Revises: d4867f3a4c0a
Create Date: 2021-12-17 15:09:31.192025

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '08433c1cee9b'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wikicarcategory',
    sa.Column('category_short_eu', sa.String(), nullable=False),
    sa.Column('category_name_de', sa.String(), nullable=False),
    sa.Column('category_name_en', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('category_short_eu')
    )
    op.create_index(op.f('ix_wikicarcategory_category_name_de'), 'wikicarcategory', ['category_name_de'], unique=True)
    op.create_index(op.f('ix_wikicarcategory_category_name_en'), 'wikicarcategory', ['category_name_en'], unique=True)
    op.create_index(op.f('ix_wikicarcategory_category_short_eu'), 'wikicarcategory', ['category_short_eu'], unique=True)
    op.create_table('wikicar',
    sa.Column('hash_id', sa.CHAR(length=32), nullable=False),
    sa.Column('wiki_name', sa.String(), nullable=False),
    sa.Column('category_short_eu', sa.String(), nullable=True),
    sa.Column('brand_name', sa.String(), nullable=False),
    sa.Column('car_name', sa.String(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('page_language', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_short_eu'], ['wikicarcategory.category_short_eu'], ),
    sa.PrimaryKeyConstraint('hash_id'),
    sa.UniqueConstraint('hash_id')
    )
    op.create_index(op.f('ix_wikicar_brand_name'), 'wikicar', ['brand_name'], unique=False)
    op.create_index(op.f('ix_wikicar_car_name'), 'wikicar', ['car_name'], unique=False)
    op.create_index(op.f('ix_wikicar_category_short_eu'), 'wikicar', ['category_short_eu'], unique=False)
    op.create_index(op.f('ix_wikicar_wiki_name'), 'wikicar', ['wiki_name'], unique=False)
    op.create_table('wikicarpagetext',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash_id', sa.CHAR(length=32), nullable=False),
    sa.Column('wiki_name', sa.String(), nullable=False),
    sa.Column('brand_name', sa.String(), nullable=False),
    sa.Column('car_name', sa.String(), nullable=False),
    sa.Column('page_language', sa.String(), nullable=False),
    sa.Column('page_text', sa.String(), nullable=True),
    sa.Column('category_short_eu', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_short_eu'], ['wikicarcategory.category_short_eu'], ),
    sa.PrimaryKeyConstraint('id', 'hash_id'),
    sa.UniqueConstraint('hash_id')
    )
    op.create_index(op.f('ix_wikicarpagetext_brand_name'), 'wikicarpagetext', ['brand_name'], unique=False)
    op.create_index(op.f('ix_wikicarpagetext_car_name'), 'wikicarpagetext', ['car_name'], unique=False)
    op.create_index(op.f('ix_wikicarpagetext_category_short_eu'), 'wikicarpagetext', ['category_short_eu'], unique=False)
    op.create_index(op.f('ix_wikicarpagetext_id'), 'wikicarpagetext', ['id'], unique=True)
    op.create_index(op.f('ix_wikicarpagetext_page_language'), 'wikicarpagetext', ['page_language'], unique=False)
    op.create_index(op.f('ix_wikicarpagetext_wiki_name'), 'wikicarpagetext', ['wiki_name'], unique=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_wikicarpagetext_wiki_name'), table_name='wikicarpagetext')
    op.drop_index(op.f('ix_wikicarpagetext_page_language'), table_name='wikicarpagetext')
    op.drop_index(op.f('ix_wikicarpagetext_id'), table_name='wikicarpagetext')
    op.drop_index(op.f('ix_wikicarpagetext_category_short_eu'), table_name='wikicarpagetext')
    op.drop_index(op.f('ix_wikicarpagetext_car_name'), table_name='wikicarpagetext')
    op.drop_index(op.f('ix_wikicarpagetext_brand_name'), table_name='wikicarpagetext')
    op.drop_table('wikicarpagetext')
    op.drop_index(op.f('ix_wikicar_wiki_name'), table_name='wikicar')
    op.drop_index(op.f('ix_wikicar_category_short_eu'), table_name='wikicar')
    op.drop_index(op.f('ix_wikicar_car_name'), table_name='wikicar')
    op.drop_index(op.f('ix_wikicar_brand_name'), table_name='wikicar')
    op.drop_table('wikicar')
    op.drop_index(op.f('ix_wikicarcategory_category_short_eu'), table_name='wikicarcategory')
    op.drop_index(op.f('ix_wikicarcategory_category_name_en'), table_name='wikicarcategory')
    op.drop_index(op.f('ix_wikicarcategory_category_name_de'), table_name='wikicarcategory')
    op.drop_table('wikicarcategory')
    # ### end Alembic commands ###
