"""Add eurostat models

Revision ID: 26aae37a85d5
Revises: eae72682f940
Create Date: 2021-12-21 18:24:02.755151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26aae37a85d5'
down_revision = 'eae72682f940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eurostatgeneralpricemodel',
    sa.Column('hash_id', sa.CHAR(length=32), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('euro_price', sa.Integer(), nullable=True),
    sa.Column('euro_ht', sa.Numeric(), nullable=True),
    sa.Column('euro_ttc', sa.Numeric(), nullable=True),
    sa.Column('euro_unit', sa.String(), nullable=False),
    sa.Column('euro_quantity', sa.Integer(), nullable=False),
    sa.Column('diesel_ht', sa.Numeric(), nullable=True),
    sa.Column('diesel_ttc', sa.Numeric(), nullable=True),
    sa.Column('diesel_unit', sa.String(), nullable=False),
    sa.Column('diesel_quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('hash_id', 'date'),
    sa.UniqueConstraint('date'),
    sa.UniqueConstraint('hash_id')
    )
    op.create_table('eurostatcountryprice',
    sa.Column('hash_id', sa.CHAR(length=32), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('country_alpha_2', sa.String(), nullable=False),
    sa.Column('taux', sa.Float(), nullable=True),
    sa.Column('euro_price', sa.Integer(), nullable=True),
    sa.Column('euro_ht', sa.Numeric(), nullable=True),
    sa.Column('euro_ttc', sa.Numeric(), nullable=True),
    sa.Column('euro_unit', sa.String(), nullable=False),
    sa.Column('euro_quantity', sa.Integer(), nullable=False),
    sa.Column('diesel_ht', sa.Numeric(), nullable=True),
    sa.Column('diesel_ttc', sa.Numeric(), nullable=True),
    sa.Column('diesel_unit', sa.String(), nullable=False),
    sa.Column('diesel_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_alpha_2'], ['countrydata.country_alpha_2'], ),
    sa.PrimaryKeyConstraint('hash_id')
    )
    op.create_index(op.f('ix_eurostatcountryprice_country_alpha_2'), 'eurostatcountryprice', ['country_alpha_2'], unique=False)
    op.create_index(op.f('ix_eurostatcountryprice_date'), 'eurostatcountryprice', ['date'], unique=False)
    op.create_index(op.f('ix_eurostatcountryprice_hash_id'), 'eurostatcountryprice', ['hash_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eurostatcountryprice_hash_id'), table_name='eurostatcountryprice')
    op.drop_index(op.f('ix_eurostatcountryprice_date'), table_name='eurostatcountryprice')
    op.drop_index(op.f('ix_eurostatcountryprice_country_alpha_2'), table_name='eurostatcountryprice')
    op.drop_table('eurostatcountryprice')
    op.drop_table('eurostatgeneralpricemodel')
    # ### end Alembic commands ###
