"""Update to Integer

Revision ID: 7af6479f469b
Revises: 209d1b0b14b6
Create Date: 2021-12-29 14:28:13.002182

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "7af6479f469b"
down_revision = "209d1b0b14b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "carfueldatacar", sa.Column("emissions_co_mg_km", sa.Float(), nullable=True)
    )
    op.alter_column(
        "carfueldatacar",
        "wltp_co2",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "carfueldatacar",
        "wltp_co2_weighted",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "carfueldatacar",
        "equivalent_all_electric_range_miles",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "carfueldatacar",
        "equivalent_all_electric_range_km",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "carfueldatacar",
        "electric_range_city_miles",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "carfueldatacar",
        "electric_range_city_km",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "carfueldatacar",
        "rde_nox_urban",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "carfueldatacar",
        "rde_nox_combined",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.drop_column("carfueldatacar", "emissions_co_m   g_km")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "carfueldatacar",
        sa.Column(
            "emissions_co_m   g_km",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column(
        "carfueldatacar",
        "rde_nox_combined",
        existing_type=sa.Integer(),
        type_=postgresql.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "carfueldatacar",
        "rde_nox_urban",
        existing_type=sa.Integer(),
        type_=postgresql.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "carfueldatacar",
        "electric_range_city_km",
        existing_type=sa.Integer(),
        type_=postgresql.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "carfueldatacar",
        "electric_range_city_miles",
        existing_type=sa.Integer(),
        type_=postgresql.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "carfueldatacar",
        "equivalent_all_electric_range_km",
        existing_type=sa.Integer(),
        type_=postgresql.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "carfueldatacar",
        "equivalent_all_electric_range_miles",
        existing_type=sa.Integer(),
        type_=postgresql.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "carfueldatacar",
        "wltp_co2_weighted",
        existing_type=sa.Integer(),
        type_=postgresql.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "carfueldatacar",
        "wltp_co2",
        existing_type=sa.Integer(),
        type_=postgresql.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.drop_column("carfueldatacar", "emissions_co_mg_km")
    # ### end Alembic commands ###
