"""Add carfueldata models

Revision ID: 8feb2c432622
Revises: 08433c1cee9b
Create Date: 2021-12-19 19:05:22.692336

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8feb2c432622'
down_revision = '08433c1cee9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carfueldatacar',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('transmission', sa.String(), nullable=False),
    sa.Column('engine_capacity', sa.String(), nullable=False),
    sa.Column('fuel_type', sa.String(), nullable=False),
    sa.Column('e_consumption_miles_per_kWh', sa.Float(), nullable=True),
    sa.Column('e_consumption_wh_per_km', sa.Float(), nullable=True),
    sa.Column('maximum_range_km', sa.Float(), nullable=True),
    sa.Column('maximum_range_miles', sa.Float(), nullable=True),
    sa.Column('metric_urban_cold', sa.Float(), nullable=True),
    sa.Column('metric_extra_urban', sa.Float(), nullable=True),
    sa.Column('metric_combined', sa.Float(), nullable=True),
    sa.Column('imperial_urban_cold', sa.Float(), nullable=True),
    sa.Column('imperial_extra_urban', sa.Float(), nullable=True),
    sa.Column('imperial_combined', sa.Float(), nullable=True),
    sa.Column('co2_g_per_km', sa.Float(), nullable=True),
    sa.Column('fuel_cost_6000_miles', sa.Float(), nullable=True),
    sa.Column('fuel_cost_12000_miles', sa.Float(), nullable=True),
    sa.Column('electricity_cost', sa.Float(), nullable=True),
    sa.Column('total_cost_per_12000_miles', sa.Float(), nullable=True),
    sa.Column('euro_standard', sa.String(), nullable=True),
    sa.Column('noise_level_dB_a_', sa.Float(), nullable=True),
    sa.Column('emissions_co_mg_per_km', sa.Float(), nullable=True),
    sa.Column('thc_emissions_mg_per_km', sa.Float(), nullable=True),
    sa.Column('emissions_nox_mg_per_km', sa.Float(), nullable=True),
    sa.Column('thc_plus_nox_emissions_mg_per_km', sa.Float(), nullable=True),
    sa.Column('particulates_no_mg_per_km', sa.Float(), nullable=True),
    sa.Column('rde_nox_urban', sa.Float(), nullable=True),
    sa.Column('rde_nox_combined', sa.Float(), nullable=True),
    sa.Column('date_of_change', sa.Date(), nullable=False),
    sa.Column('wiki_hashes', sa.ARRAY(sa.CHAR(length=32)), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carfueldatacar_manufacturer'), 'carfueldatacar', ['manufacturer'], unique=False)
    op.create_table('carfueldataaveragecategorystatistics',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('vehicle_type', sa.String(), nullable=False),
    sa.Column('fuel_type', sa.String(), nullable=False),
    sa.Column('phenomenon_name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('numb_cars', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('category_short_eu', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_short_eu'], ['wikicarcategory.category_short_eu'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carfueldataaveragecategorystatistics_fuel_type'), 'carfueldataaveragecategorystatistics', ['fuel_type'], unique=False)
    op.create_index(op.f('ix_carfueldataaveragecategorystatistics_id'), 'carfueldataaveragecategorystatistics', ['id'], unique=False)
    op.create_index(op.f('ix_carfueldataaveragecategorystatistics_phenomenon_name'), 'carfueldataaveragecategorystatistics', ['phenomenon_name'], unique=False)
    op.create_index(op.f('ix_carfueldataaveragecategorystatistics_vehicle_type'), 'carfueldataaveragecategorystatistics', ['vehicle_type'], unique=False)
    op.create_index(op.f('ix_carfueldataaveragecategorystatistics_year'), 'carfueldataaveragecategorystatistics', ['year'], unique=False)
    op.create_index(op.f('ix_wikicar_hash_id'), 'wikicar', ['hash_id'], unique=False)
    op.drop_index('ix_wikicarcategory_category_short_eu', table_name='wikicarcategory')
    op.create_index(op.f('ix_wikicarcategory_category_short_eu'), 'wikicarcategory', ['category_short_eu'], unique=False)
    op.drop_index('ix_wikicarpagetext_id', table_name='wikicarpagetext')
    op.drop_constraint('wikicarpagetext_hash_id_key', 'wikicarpagetext', type_='unique')
    op.create_index(op.f('ix_wikicarpagetext_hash_id'), 'wikicarpagetext', ['hash_id'], unique=False)
    op.drop_column('wikicarpagetext', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wikicarpagetext', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_wikicarpagetext_hash_id'), table_name='wikicarpagetext')
    op.create_unique_constraint('wikicarpagetext_hash_id_key', 'wikicarpagetext', ['hash_id'])
    op.create_index('ix_wikicarpagetext_id', 'wikicarpagetext', ['id'], unique=False)
    op.drop_index(op.f('ix_wikicarcategory_category_short_eu'), table_name='wikicarcategory')
    op.create_index('ix_wikicarcategory_category_short_eu', 'wikicarcategory', ['category_short_eu'], unique=False)
    op.drop_index(op.f('ix_wikicar_hash_id'), table_name='wikicar')
    op.drop_index(op.f('ix_carfueldataaveragecategorystatistics_year'), table_name='carfueldataaveragecategorystatistics')
    op.drop_index(op.f('ix_carfueldataaveragecategorystatistics_vehicle_type'), table_name='carfueldataaveragecategorystatistics')
    op.drop_index(op.f('ix_carfueldataaveragecategorystatistics_phenomenon_name'), table_name='carfueldataaveragecategorystatistics')
    op.drop_index(op.f('ix_carfueldataaveragecategorystatistics_id'), table_name='carfueldataaveragecategorystatistics')
    op.drop_index(op.f('ix_carfueldataaveragecategorystatistics_fuel_type'), table_name='carfueldataaveragecategorystatistics')
    op.drop_table('carfueldataaveragecategorystatistics')
    op.drop_index(op.f('ix_carfueldatacar_manufacturer'), table_name='carfueldatacar')
    op.drop_table('carfueldatacar')
    # ### end Alembic commands ###
