"""Add envirocar models

Revision ID: 936918094389
Revises: 26aae37a85d5
Create Date: 2021-12-21 18:52:26.910886

"""
import sqlalchemy as sa
from geoalchemy2.types import Geometry

from alembic import op

# revision identifiers, used by Alembic.
revision = "936918094389"
down_revision = "26aae37a85d5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "envirocarphenomenon",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("unit", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_index(
        op.f("ix_envirocarphenomenon_name"),
        "envirocarphenomenon",
        ["name"],
        unique=False,
    )
    op.create_table(
        "envirocarsensor",
        sa.Column("sensor_id", sa.String(), nullable=False),
        sa.Column("sensor_type", sa.String(), nullable=False),
        sa.Column("car_model", sa.String(), nullable=False),
        sa.Column("car_manufacturer", sa.String(), nullable=False),
        sa.Column("fuel_type", sa.String(), nullable=False),
        sa.Column("construction_year", sa.Integer(), nullable=False),
        sa.Column("wiki_hashes", sa.ARRAY(sa.CHAR(length=32)), nullable=True),
        sa.PrimaryKeyConstraint("sensor_id"),
    )
    op.create_index(
        op.f("ix_envirocarsensor_sensor_id"),
        "envirocarsensor",
        ["sensor_id"],
        unique=True,
    )
    op.create_table(
        "matchedwikienvirocar",
        sa.Column("object_hash", sa.CHAR(length=32), nullable=False),
        sa.Column("envirocar_sensor_id", sa.String(), nullable=True),
        sa.Column("car_hash_id", sa.CHAR(length=32), nullable=False),
        sa.PrimaryKeyConstraint("object_hash"),
    )
    op.create_index(
        op.f("ix_matchedwikienvirocar_car_hash_id"),
        "matchedwikienvirocar",
        ["car_hash_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_matchedwikienvirocar_envirocar_sensor_id"),
        "matchedwikienvirocar",
        ["envirocar_sensor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_matchedwikienvirocar_object_hash"),
        "matchedwikienvirocar",
        ["object_hash"],
        unique=False,
    )
    op.create_table(
        "envirocaraveragecategorystatistics",
        sa.Column("hash_id", sa.CHAR(length=32), nullable=False),
        sa.Column("vehicle_type", sa.String(), nullable=False),
        sa.Column("fuel_type", sa.String(), nullable=False),
        sa.Column("phenomenon_name", sa.String(), nullable=False),
        sa.Column("max", sa.Float(asdecimal=True), nullable=True),
        sa.Column("average", sa.Float(asdecimal=True), nullable=True),
        sa.Column("min", sa.Float(asdecimal=True), nullable=True),
        sa.Column("measurements", sa.Integer(), nullable=False),
        sa.Column("numb_sensors", sa.Integer(), nullable=False),
        sa.Column("category_short_eu", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_short_eu"], ["wikicarcategory.category_short_eu"],
        ),
        sa.ForeignKeyConstraint(["phenomenon_name"], ["envirocarphenomenon.name"],),
        sa.PrimaryKeyConstraint("hash_id"),
    )
    op.create_index(
        op.f("ix_envirocaraveragecategorystatistics_fuel_type"),
        "envirocaraveragecategorystatistics",
        ["fuel_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_envirocaraveragecategorystatistics_hash_id"),
        "envirocaraveragecategorystatistics",
        ["hash_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_envirocaraveragecategorystatistics_phenomenon_name"),
        "envirocaraveragecategorystatistics",
        ["phenomenon_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_envirocaraveragecategorystatistics_vehicle_type"),
        "envirocaraveragecategorystatistics",
        ["vehicle_type"],
        unique=False,
    )
    op.create_table(
        "envirocaraveragemanufacturerstatistic",
        sa.Column("hash_id", sa.CHAR(length=32), nullable=False),
        sa.Column("manufacturer", sa.String(), nullable=False),
        sa.Column("vehicle_type", sa.String(), nullable=False),
        sa.Column("fuel_type", sa.String(), nullable=False),
        sa.Column("phenomenon_name", sa.String(), nullable=False),
        sa.Column("max", sa.Float(asdecimal=True), nullable=True),
        sa.Column("average", sa.Float(asdecimal=True), nullable=True),
        sa.Column("min", sa.Float(asdecimal=True), nullable=True),
        sa.Column("measurements", sa.Integer(), nullable=False),
        sa.Column("numb_sensors", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["phenomenon_name"], ["envirocarphenomenon.name"],),
        sa.PrimaryKeyConstraint("hash_id"),
    )
    op.create_index(
        op.f("ix_envirocaraveragemanufacturerstatistic_fuel_type"),
        "envirocaraveragemanufacturerstatistic",
        ["fuel_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_envirocaraveragemanufacturerstatistic_hash_id"),
        "envirocaraveragemanufacturerstatistic",
        ["hash_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_envirocaraveragemanufacturerstatistic_manufacturer"),
        "envirocaraveragemanufacturerstatistic",
        ["manufacturer"],
        unique=False,
    )
    op.create_index(
        op.f("ix_envirocaraveragemanufacturerstatistic_phenomenon_name"),
        "envirocaraveragemanufacturerstatistic",
        ["phenomenon_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_envirocaraveragemanufacturerstatistic_vehicle_type"),
        "envirocaraveragemanufacturerstatistic",
        ["vehicle_type"],
        unique=False,
    )
    op.create_table(
        "envirocaraveragevehicletypestatistic",
        sa.Column("hash_id", sa.CHAR(length=32), nullable=False),
        sa.Column("vehicle_type", sa.String(), nullable=False),
        sa.Column("fuel_type", sa.String(), nullable=False),
        sa.Column("phenomenon_name", sa.String(), nullable=False),
        sa.Column("max", sa.Float(asdecimal=True), nullable=True),
        sa.Column("average", sa.Float(asdecimal=True), nullable=True),
        sa.Column("min", sa.Float(asdecimal=True), nullable=True),
        sa.Column("measurements", sa.Integer(), nullable=False),
        sa.Column("numb_sensors", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["phenomenon_name"], ["envirocarphenomenon.name"],),
        sa.PrimaryKeyConstraint("hash_id"),
    )
    op.create_index(
        op.f("ix_envirocaraveragevehicletypestatistic_fuel_type"),
        "envirocaraveragevehicletypestatistic",
        ["fuel_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_envirocaraveragevehicletypestatistic_hash_id"),
        "envirocaraveragevehicletypestatistic",
        ["hash_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_envirocaraveragevehicletypestatistic_phenomenon_name"),
        "envirocaraveragevehicletypestatistic",
        ["phenomenon_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_envirocaraveragevehicletypestatistic_vehicle_type"),
        "envirocaraveragevehicletypestatistic",
        ["vehicle_type"],
        unique=False,
    )
    op.create_table(
        "envirocarsensorstatistic",
        sa.Column("hash_id", sa.CHAR(length=32), nullable=False),
        sa.Column("sensor_id", sa.String(), nullable=False),
        sa.Column("phenomenon_name", sa.String(), nullable=False),
        sa.Column("max", sa.Float(asdecimal=True), nullable=True),
        sa.Column("avg", sa.Float(asdecimal=True), nullable=True),
        sa.Column("min", sa.Float(asdecimal=True), nullable=True),
        sa.Column("numb_measurements", sa.Integer(), nullable=True),
        sa.Column("numb_tracks", sa.Integer(), nullable=True),
        sa.Column("numb_users", sa.Integer(), nullable=True),
        sa.Column("numb_sensors", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["phenomenon_name"], ["envirocarphenomenon.name"],),
        sa.ForeignKeyConstraint(["sensor_id"], ["envirocarsensor.sensor_id"],),
        sa.PrimaryKeyConstraint("hash_id"),
    )
    op.create_index(
        op.f("ix_envirocarsensorstatistic_hash_id"),
        "envirocarsensorstatistic",
        ["hash_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_envirocarsensorstatistic_phenomenon_name"),
        "envirocarsensorstatistic",
        ["phenomenon_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_envirocarsensorstatistic_sensor_id"),
        "envirocarsensorstatistic",
        ["sensor_id"],
        unique=False,
    )
    op.create_table(
        "envirocartrack",
        sa.Column("track_id", sa.String(), nullable=False),
        sa.Column("sensor_id", sa.String(), nullable=False),
        sa.Column("track_length", sa.Float(asdecimal=True), nullable=True),
        sa.Column(
            "geom",
            Geometry(
                geometry_type="LINESTRING",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["sensor_id"], ["envirocarsensor.sensor_id"],),
        sa.PrimaryKeyConstraint("track_id"),
    )
    op.create_index(
        op.f("ix_envirocartrack_sensor_id"),
        "envirocartrack",
        ["sensor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_envirocartrack_track_id"), "envirocartrack", ["track_id"], unique=True
    )
    op.create_table(
        "envirocartrackfeature",
        sa.Column("track_measurement_id", sa.String(), nullable=False),
        sa.Column("sensor_id", sa.String(), nullable=False),
        sa.Column("track_id", sa.String(), nullable=False),
        sa.Column(
            "geom",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["sensor_id"], ["envirocarsensor.sensor_id"],),
        sa.ForeignKeyConstraint(["track_id"], ["envirocartrack.track_id"],),
        sa.PrimaryKeyConstraint("track_measurement_id"),
    )
    op.create_index(
        op.f("ix_envirocartrackfeature_sensor_id"),
        "envirocartrackfeature",
        ["sensor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_envirocartrackfeature_track_id"),
        "envirocartrackfeature",
        ["track_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_envirocartrackfeature_track_measurement_id"),
        "envirocartrackfeature",
        ["track_measurement_id"],
        unique=True,
    )
    op.create_table(
        "envirocartrackstatistic",
        sa.Column("hash_id", sa.CHAR(length=32), nullable=False),
        sa.Column("track_id", sa.String(), nullable=False),
        sa.Column("phenomenon_name", sa.String(), nullable=False),
        sa.Column("max", sa.Float(asdecimal=True), nullable=True),
        sa.Column("avg", sa.Float(asdecimal=True), nullable=True),
        sa.Column("min", sa.Float(asdecimal=True), nullable=True),
        sa.Column("numb_measurements", sa.Integer(), nullable=True),
        sa.Column("numb_tracks", sa.Float(asdecimal=True), nullable=True),
        sa.Column("numb_users", sa.Float(asdecimal=True), nullable=True),
        sa.Column("numb_sensors", sa.Float(asdecimal=True), nullable=True),
        sa.ForeignKeyConstraint(["phenomenon_name"], ["envirocarphenomenon.name"],),
        sa.ForeignKeyConstraint(["track_id"], ["envirocartrack.track_id"],),
        sa.PrimaryKeyConstraint("hash_id"),
    )
    op.create_index(
        op.f("ix_envirocartrackstatistic_hash_id"),
        "envirocartrackstatistic",
        ["hash_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_envirocartrackstatistic_phenomenon_name"),
        "envirocartrackstatistic",
        ["phenomenon_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_envirocartrackstatistic_track_id"),
        "envirocartrackstatistic",
        ["track_id"],
        unique=False,
    )
    op.create_table(
        "envirocartrackmeasurement",
        sa.Column("hash_id", sa.CHAR(length=32), nullable=False),
        sa.Column("track_measurement_id", sa.String(), nullable=False),
        sa.Column("track_id", sa.String(), nullable=False),
        sa.Column("sensor_id", sa.String(), nullable=False),
        sa.Column("phenomenon_name", sa.String(), nullable=False),
        sa.Column("phenomenon_value", sa.Float(asdecimal=True), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["phenomenon_name"], ["envirocarphenomenon.name"],),
        sa.ForeignKeyConstraint(["sensor_id"], ["envirocarsensor.sensor_id"],),
        sa.ForeignKeyConstraint(["track_id"], ["envirocartrack.track_id"],),
        sa.ForeignKeyConstraint(
            ["track_measurement_id"], ["envirocartrackfeature.track_measurement_id"],
        ),
        sa.PrimaryKeyConstraint("hash_id"),
    )
    op.create_index(
        op.f("ix_envirocartrackmeasurement_date"),
        "envirocartrackmeasurement",
        ["date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_envirocartrackmeasurement_hash_id"),
        "envirocartrackmeasurement",
        ["hash_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_envirocartrackmeasurement_phenomenon_name"),
        "envirocartrackmeasurement",
        ["phenomenon_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_envirocartrackmeasurement_sensor_id"),
        "envirocartrackmeasurement",
        ["sensor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_envirocartrackmeasurement_track_id"),
        "envirocartrackmeasurement",
        ["track_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_envirocartrackmeasurement_track_measurement_id"),
        "envirocartrackmeasurement",
        ["track_measurement_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_envirocartrackmeasurement_track_measurement_id"),
        table_name="envirocartrackmeasurement",
    )
    op.drop_index(
        op.f("ix_envirocartrackmeasurement_track_id"),
        table_name="envirocartrackmeasurement",
    )
    op.drop_index(
        op.f("ix_envirocartrackmeasurement_sensor_id"),
        table_name="envirocartrackmeasurement",
    )
    op.drop_index(
        op.f("ix_envirocartrackmeasurement_phenomenon_name"),
        table_name="envirocartrackmeasurement",
    )
    op.drop_index(
        op.f("ix_envirocartrackmeasurement_hash_id"),
        table_name="envirocartrackmeasurement",
    )
    op.drop_index(
        op.f("ix_envirocartrackmeasurement_date"),
        table_name="envirocartrackmeasurement",
    )
    op.drop_table("envirocartrackmeasurement")
    op.drop_index(
        op.f("ix_envirocartrackstatistic_track_id"),
        table_name="envirocartrackstatistic",
    )
    op.drop_index(
        op.f("ix_envirocartrackstatistic_phenomenon_name"),
        table_name="envirocartrackstatistic",
    )
    op.drop_index(
        op.f("ix_envirocartrackstatistic_hash_id"), table_name="envirocartrackstatistic"
    )
    op.drop_table("envirocartrackstatistic")
    op.drop_index(
        op.f("ix_envirocartrackfeature_track_measurement_id"),
        table_name="envirocartrackfeature",
    )
    op.drop_index(
        op.f("ix_envirocartrackfeature_track_id"), table_name="envirocartrackfeature"
    )
    op.drop_index(
        op.f("ix_envirocartrackfeature_sensor_id"), table_name="envirocartrackfeature"
    )
    op.drop_table("envirocartrackfeature")
    op.drop_index(op.f("ix_envirocartrack_track_id"), table_name="envirocartrack")
    op.drop_index(op.f("ix_envirocartrack_sensor_id"), table_name="envirocartrack")
    op.drop_table("envirocartrack")
    op.drop_index(
        op.f("ix_envirocarsensorstatistic_sensor_id"),
        table_name="envirocarsensorstatistic",
    )
    op.drop_index(
        op.f("ix_envirocarsensorstatistic_phenomenon_name"),
        table_name="envirocarsensorstatistic",
    )
    op.drop_index(
        op.f("ix_envirocarsensorstatistic_hash_id"),
        table_name="envirocarsensorstatistic",
    )
    op.drop_table("envirocarsensorstatistic")
    op.drop_index(
        op.f("ix_envirocaraveragevehicletypestatistic_vehicle_type"),
        table_name="envirocaraveragevehicletypestatistic",
    )
    op.drop_index(
        op.f("ix_envirocaraveragevehicletypestatistic_phenomenon_name"),
        table_name="envirocaraveragevehicletypestatistic",
    )
    op.drop_index(
        op.f("ix_envirocaraveragevehicletypestatistic_hash_id"),
        table_name="envirocaraveragevehicletypestatistic",
    )
    op.drop_index(
        op.f("ix_envirocaraveragevehicletypestatistic_fuel_type"),
        table_name="envirocaraveragevehicletypestatistic",
    )
    op.drop_table("envirocaraveragevehicletypestatistic")
    op.drop_index(
        op.f("ix_envirocaraveragemanufacturerstatistic_vehicle_type"),
        table_name="envirocaraveragemanufacturerstatistic",
    )
    op.drop_index(
        op.f("ix_envirocaraveragemanufacturerstatistic_phenomenon_name"),
        table_name="envirocaraveragemanufacturerstatistic",
    )
    op.drop_index(
        op.f("ix_envirocaraveragemanufacturerstatistic_manufacturer"),
        table_name="envirocaraveragemanufacturerstatistic",
    )
    op.drop_index(
        op.f("ix_envirocaraveragemanufacturerstatistic_hash_id"),
        table_name="envirocaraveragemanufacturerstatistic",
    )
    op.drop_index(
        op.f("ix_envirocaraveragemanufacturerstatistic_fuel_type"),
        table_name="envirocaraveragemanufacturerstatistic",
    )
    op.drop_table("envirocaraveragemanufacturerstatistic")
    op.drop_index(
        op.f("ix_envirocaraveragecategorystatistics_vehicle_type"),
        table_name="envirocaraveragecategorystatistics",
    )
    op.drop_index(
        op.f("ix_envirocaraveragecategorystatistics_phenomenon_name"),
        table_name="envirocaraveragecategorystatistics",
    )
    op.drop_index(
        op.f("ix_envirocaraveragecategorystatistics_hash_id"),
        table_name="envirocaraveragecategorystatistics",
    )
    op.drop_index(
        op.f("ix_envirocaraveragecategorystatistics_fuel_type"),
        table_name="envirocaraveragecategorystatistics",
    )
    op.drop_table("envirocaraveragecategorystatistics")
    op.drop_index(
        op.f("ix_matchedwikienvirocar_object_hash"), table_name="matchedwikienvirocar"
    )
    op.drop_index(
        op.f("ix_matchedwikienvirocar_envirocar_sensor_id"),
        table_name="matchedwikienvirocar",
    )
    op.drop_index(
        op.f("ix_matchedwikienvirocar_car_hash_id"), table_name="matchedwikienvirocar"
    )
    op.drop_table("matchedwikienvirocar")
    op.drop_index(op.f("ix_envirocarsensor_sensor_id"), table_name="envirocarsensor")
    op.drop_table("envirocarsensor")
    op.drop_index(op.f("ix_envirocarphenomenon_name"), table_name="envirocarphenomenon")
    op.drop_table("envirocarphenomenon")
    # ### end Alembic commands ###
