"""Add country data models

Revision ID: eae72682f940
Revises: 73883d2da3d5
Create Date: 2021-12-21 17:50:48.390692

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2.types import Geometry

# revision identifiers, used by Alembic.
revision = 'eae72682f940'
down_revision = '73883d2da3d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countrydata',
    sa.Column('country_name', sa.String(), nullable=False),
    sa.Column('country_alpha_2', sa.String(), nullable=True),
    sa.Column('country_alpha_3', sa.VARCHAR(), nullable=True),
    sa.Column('country_numeric', sa.Integer(), nullable=True),
    sa.Column('country_currency_code', sa.String(), nullable=True),
    sa.Column('country_currency_name', sa.String(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('country_name')
    )
    op.create_index(op.f('ix_countrydata_country_alpha_2'), 'countrydata', ['country_alpha_2'], unique=True)
    op.create_index(op.f('ix_countrydata_country_alpha_3'), 'countrydata', ['country_alpha_3'], unique=True)
    op.create_index(op.f('ix_countrydata_country_currency_code'), 'countrydata', ['country_currency_code'], unique=False)
    op.create_index(op.f('ix_countrydata_country_currency_name'), 'countrydata', ['country_currency_name'], unique=False)
    op.create_index(op.f('ix_countrydata_country_name'), 'countrydata', ['country_name'], unique=False)
    op.create_index(op.f('ix_countrydata_country_numeric'), 'countrydata', ['country_numeric'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_countrydata_country_numeric'), table_name='countrydata')
    op.drop_index(op.f('ix_countrydata_country_name'), table_name='countrydata')
    op.drop_index(op.f('ix_countrydata_country_currency_name'), table_name='countrydata')
    op.drop_index(op.f('ix_countrydata_country_currency_code'), table_name='countrydata')
    op.drop_index(op.f('ix_countrydata_country_alpha_3'), table_name='countrydata')
    op.drop_index(op.f('ix_countrydata_country_alpha_2'), table_name='countrydata')
    op.drop_table('countrydata')
    # ### end Alembic commands ###
