name: Continous Integration

on:
  pull_request:
    branches: '**'

jobs:
#  lint:
#    runs-on: ubuntu-20.04
#    steps:
#      - name: checkout
#        uses: actions/checkout@v2
#      - name: Set up testing Python ${{ matrix.config.python-version }}
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.9
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip tox
#      - name: Install Poetry
#        uses: snok/install-poetry@v1
#        with:
#          version: 1.1.11
#          virtualenvs-create: true
#          virtualenvs-in-project: true
#          installer-parallel: true
#      - name: Run tox lint
#        run: |
#          cd "$PWD/backend/"
#          poetry run tox -e lint
  linux-tests:
#    needs:
#      - lint
    strategy:
      fail-fast: false
      matrix:
        config:
          - python-version: '3.8'
            tox: py38
          - python-version: '3.9'
            tox: py39
          - python-version: '3.10'
            tox: py310
        poetry-version: [ 1.1.11 ]
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    services:
      queue:
        image: rabbitmq:3
        ports:
          - 5672:5672
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: dontchangethis
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    environment: tox-testing
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up testing Python ${{ matrix.config.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.config.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip tox
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ matrix.poetry-version }}
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Set github.env
        run: echo "DEBUGGING_CONFIG=${GITHUB_WORKSPACE}/backend/github.env" >> $GITHUB_ENV
      - name: Run tox
        env:
          GITHUB_CELERY_BROKER_URL: "amqp://guest@localhost:5672//"
          GITHUB_POSTGRES_SERVER: localhost
          GITHUB_POSTGRES_USER: postgres
          GITHUB_POSTGRES_PASSWORD: dontchangethis
          GITHUB_POSTGRES_DB: test_db
          GITHUB_POSTGRES_PORT: 5432
        run: |
          cd "$PWD/backend/"
          ls -sahl "$DEBUGGING_CONFIG"
          cat "$DEBUGGING_CONFIG" >> $GITHUB_ENV
          export CELERY_BROKER_URL="$GITHUB_CELERY_BROKER_URL"
          export POSTGRES_SERVER="$GITHUB_POSTGRES_SERVER"
          export POSTGRES_USER="$GITHUB_POSTGRES_USER"
          export POSTGRES_PASSWORD="$GITHUB_POSTGRES_PASSWORD"
          export POSTGRES_DB="$GITHUB_POSTGRES_DB"
          export POSTGRES_PORT="$GITHUB_POSTGRES_PORT"
          export TOX_TESTENV_PASSENV=*
          poetry run tox -e pytest-github-${{ matrix.config.tox }}
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v1
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          flags: unittests
#          env_vars: OS,PYTHON
#          name: codecov-umbrella
#          fail_ci_if_error: true
#          verbose: true
